package com.solvd.developmentCompany;

import com.solvd.developmentCompany.utils.ConnectionFactory;
import com.solvd.developmentCompany.db.mappers.IMachinesMapper;
import com.solvd.developmentCompany.models.inventory.Machines;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

public class MachinesServiceTest {

    private final SqlSessionFactory sqlSessionFactory = ConnectionFactory.sqlSessionFactory;

    @Test
    public void createMachineAssetTest() {
        try (SqlSession session = sqlSessionFactory.openSession(true)) { // Open with auto-commit enabled
            IMachinesMapper machineMapper = session.getMapper(IMachinesMapper.class);

            Machines newMachine = new Machines();
            newMachine.setMachineName("CAT 320 Excavator");
            newMachine.setSerialNumber("SN-CAT320-2026");
            newMachine.setPlateNumber("PL-9988-X");
            newMachine.setValue("145000.00");
            newMachine.setCompanyProperty(true);
            newMachine.setAssigned(false);
            newMachine.setContractorId(null);
            newMachine.setCurrentProjectId(null);

            machineMapper.insert(newMachine);

            Assert.assertNotNull(newMachine.getId(), "Machine ID should be automatically generated by MySQL auto-increment.");

            Machines fetched = machineMapper.getById(newMachine.getId());
            Assert.assertNotNull(fetched, "Should successfully read back the newly created asset from the database.");
            Assert.assertEquals(fetched.getMachineName(), "CAT 320 Excavator", "Saved machine name should match target input.");
        }
    }

    @Test
    public void updateMachineAssignmentTest() {
        try (SqlSession session = sqlSessionFactory.openSession(true)) {
            IMachinesMapper machineMapper = session.getMapper(IMachinesMapper.class);
            SoftAssert softAssert = new SoftAssert();

            Machines machine = new Machines();
            machine.setMachineName("Test truck to update");
            machine.setSerialNumber("TEST-2026");
            machine.setPlateNumber("PL-4567-S");
            machine.setValue("145000.00");
            machine.setCompanyProperty(true);
            machine.setAssigned(false);
            machine.setContractorId(null);
            machine.setCurrentProjectId(null);

            machineMapper.insert(machine);

            Assert.assertNotNull(machine.getId(), "Test prerequisite failed: Machine ID was not generated.");

            machine.setAssigned(true);
            machine.setContractorId(null);
            machine.setCurrentProjectId(null);
            machine.setValue("140000.00");

            machineMapper.update(machine);

            Machines updatedMachine = machineMapper.getById(machine.getId());
            Assert.assertNotNull(updatedMachine, "Failed to retrieve the updated machine from the DB.");

            softAssert.assertTrue(updatedMachine.isAssigned(), "Machine assignment state flag update failed.");
            softAssert.assertEquals(updatedMachine.getValue(), "140000.00", "Asset financial valuation tracking update misaligned.");

            softAssert.assertAll();
        }
    }

    @Test
    public void getMachineByNonExistentIdTest() {
        try (SqlSession session = sqlSessionFactory.openSession()) {
            IMachinesMapper machineMapper = session.getMapper(IMachinesMapper.class);

            Long nonExistentId = 999999L;

            Machines missingMachine = machineMapper.getById(nonExistentId);

            Assert.assertNull(missingMachine, "Querying a non-existent machine ID should return null.");
        }
    }

    @AfterMethod
    public void tearDownTestData() {
        String cleanupSql = "DELETE FROM Machines WHERE serial_number = ?";

        try (SqlSession session = sqlSessionFactory.openSession(true);
             java.sql.PreparedStatement stmt = session.getConnection().prepareStatement(cleanupSql)) {

            stmt.setString(1, "SN-CAT320-2026");
            stmt.setString(2, "TEST-2026");
            stmt.executeUpdate();

        } catch (Exception e) {

        }
    }
}