package com.solvd.developmentCompany;

import com.solvd.developmentCompany.services.ProjectService;
import com.solvd.developmentCompany.models.buildings.Project;
import com.solvd.developmentCompany.utils.ConnectionFactory;
import org.apache.ibatis.session.SqlSession;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;
import java.util.Date;

public class ProjectServiceTest {

    private ProjectService projectService;

    @BeforeClass
    public void setup() {
        this.projectService = new ProjectService();
    }

    @Test
    public void createProjectTest() {
        Project project = new Project();
        project.setProjectName("East Side Library Renovation");
        project.setBuildingId(1L);
        project.setProjectLeadId(6L);
        project.setStartDate(new Date());
        project.setEstimatedFinishDate(new Date(System.currentTimeMillis() + 31536000000L)); // +1 year
        project.setStatus("Planning");

        projectService.createProject(project);

        Assert.assertNotNull(project.getId(), "Project ID should be auto-generated by MyBatis.");
    }

    @Test
    public void updateProjectStatusWithSoftAssertTest() {
        Project project = new Project();
        project.setProjectName("Subdivision Road Infrastructure");
        project.setBuildingId(2L);
        project.setProjectLeadId(11L);
        project.setStartDate(new Date());
        project.setStatus("Planning");

        projectService.createProject(project);

        String targetStatus = "In progress";
        project.setStatus(targetStatus);
        projectService.updateProject(project);

        SoftAssert softAssert = new SoftAssert();
        Project updatedProject = projectService.getProjectById(project.getId());

        softAssert.assertNotNull(updatedProject, "Updated project should exist in the DB.");
        softAssert.assertEquals(updatedProject.getStatus(), targetStatus, "Status should have advanced to 'In Progress'.");
        softAssert.assertEquals(updatedProject.getProjectName(), "Subdivision Road Infrastructure", "Project name should not have mutated.");

        softAssert.assertAll();
    }

    @AfterMethod
    public void tearDownTestData() {
        String cleanupSql = "DELETE FROM Project WHERE project_name = ? OR project_name = ?";

        try (SqlSession session = ConnectionFactory.sqlSessionFactory.openSession(true);
             java.sql.PreparedStatement stmt = session.getConnection().prepareStatement(cleanupSql)) {

            stmt.setString(1, "East Side Library Renovation");
            stmt.setString(2, "Subdivision Road Infrastructure");
            stmt.executeUpdate();

        } catch (Exception e) {

        }

        }

}